[package]
name = "share-ringbuf"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap.workspace = true
nix.workspace = true
snafu.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
